<center> Практична робота №2 </center>
<center> з дисципліни «Аналіз даних з використанням Python» </center>
<center> на тему «Основи NumPy: робота з об'єктом ndarray, індексація NumPy масивів» </center>
<center> Варіант №3 </center>

<div style="margin-left: 80%;"> Виконав: </div>
<div style="margin-left: 80%;"> ст. гр. АС-227 </div>
<div style="margin-left: 80%;"> Бліняєв В.О. </div>
<div style="margin-left: 80%;"> Перевірив: </div>
<div style="margin-left: 80%;"> ст. в. Штефан Н.З. </div>


### Завдання 1

#### Part 1: Variables, Strings, and Numbers

In [2]:
import numpy

In [55]:
a=3
b=6
c=1
n=1
m=15

1.Створити вектор нульових значень (довжиною a)

In [56]:
v1=numpy.zeros(a)
v1

array([0., 0., 0.])

2.Створити вектор нульових значень (довжиною b), змінити (b-4) елемент на значення с.

In [94]:
v2=numpy.zeros(b)
v2

array([0., 0., 0., 0., 0., 0.])

In [95]:
v2[4]=c
v2

array([0., 0., 0., 0., 1., 0.])

3.Створити вектор із значеннями в діапазоні від n до m

In [59]:
v3=numpy.arange(n,m)
v3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

4.Розгорнути вектор (перший елемент стає останнім)

In [60]:
f_e=v3[0]
v3=v3[1:]+[f_e]
v3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

#### Exercises

In [61]:
# Hello World - variable
mine_message = "Hello World!"
print(mine_message)

# One Variable, Two Messages
mine_message = "World Hello!"
print(mine_message)

Hello World!
World Hello!


In [62]:
my_string = "This is a double-quoted string."
my_string = 'This is a single-quoted string.'
quote = "Linus Torvalds once said, 'Any program is only as good as it is useful.'"

In [63]:
first_name = 'eric'
print(first_name)
print(first_name.title())

eric
Eric


In [64]:
first_name = 'eric'
print(first_name)
print(first_name.title())
print(first_name.upper())

first_name = 'Eric'
print(first_name.lower())

eric
Eric
ERIC
eric


In [65]:
first_name = 'ada'
last_name = 'lovelace'
full_name = first_name + ' ' + last_name
print(full_name.title())

Ada Lovelace


In [66]:
first_name = 'ada'
last_name = 'lovelace'
full_name = first_name + ' ' + last_name
message = full_name.title() + ' ' + "was considered the world's first computer programmer."
print(message)

Ada Lovelace was considered the world's first computer programmer.


In [67]:
print("Hello everyone!")
print("\tHello everyone!")
print("Hello \teveryone!")

print("Hello everyone!")
print("\nHello everyone!")
print("Hello \neveryone!")
print("\n\n\nHello everyone!")

Hello everyone!
	Hello everyone!
Hello 	everyone!
Hello everyone!

Hello everyone!
Hello 
everyone!



Hello everyone!


In [68]:
name = ' eric '
print(name.lstrip())
print(name.rstrip())
print(name.strip())

eric 
 eric
eric


#### Exercises

In [69]:
# Someone Said
st_quote = "“If you wait by the river long enough, the bodies of your enemies will float by.” ― Sun Tzu "
print(st_quote)

# First Name Cases
f_name = "vladyslav"
print(f_name.lower())
print(f_name.title())
print(f_name.upper())

# Full Name
first_name = "Vladyslav"
last_name = "Bliniaev"
full_name = first_name + ' ' + last_name
print(full_name)

# About This Person
first_name = "Sun"
last_name = "Tzu"
full_name = first_name + ' ' + last_name
message = full_name.title() + ' ' + "was a Chinese philosopher"
print(message)

# Name Strip
name = " Vladyslav "
print(name.lstrip())
print(name.rstrip())
print(name.strip())

“If you wait by the river long enough, the bodies of your enemies will float by.” ― Sun Tzu 
vladyslav
Vladyslav
VLADYSLAV
Vladyslav Bliniaev
Sun Tzu was a Chinese philosopher
Vladyslav 
 Vladyslav
Vladyslav


In [70]:
print(3 + 2)
print(3 - 2)
print(3 * 2)
print(3 / 2)
print(3 ** 2)

standard_order = 2 + 3 * 4
print(standard_order)
my_order = (2 + 3) * 4
print(my_order)

print(0.1 + 0.1)

5
1
6
1.5
9
14
20
0.2


In [71]:
# This line is a comment.
print("This line is not a comment, it is code.")

This line is not a comment, it is code.


#### Exercises

In [72]:
# Arithmetic
print(1 + 1)
print(1 - 1)
print(1 * 1)
print(1 / 1)
print(1 ** 1)

print("\n")

# Order of Operations
print(4 + 8 / 2 * 4)
print((4 + 8) / (2 * 4))

2
0
1
1.0
1


20.0
1.5


#### Part 2: Introducing Functions

In [73]:
def thank_you(name):
    # This function prints a two-line personalized thank you message.
    print("\nYou are doing good work, %s!" % name)
    print("Thank you very much for your efforts on this project.")


thank_you('Adriana')
thank_you('Billy')
thank_you('Caroline')


You are doing good work, Adriana!
Thank you very much for your efforts on this project.

You are doing good work, Billy!
Thank you very much for your efforts on this project.

You are doing good work, Caroline!
Thank you very much for your efforts on this project.


In [74]:
def get_number_word(number):
    # Takes in a numerical value, and returns
    # the word corresponding to that number.
    if number == 0:
        return 'zero'
    elif number == 1:
        return 'one'
    elif number == 2:
        return 'two'
    elif number == 3:
        return 'three'
    return None


# Let's try out our function.
for current_number in range(0, 4):
    number_word = get_number_word(current_number)
    print(current_number, number_word)

0 zero
1 one
2 two
3 three


#### Part 3: Lists and Tuples

In [75]:
students = ['bernice', 'aaron', 'cody']
for student in students:
    print("Hello, " + student.title() + "!")

Hello, Bernice!
Hello, Aaron!
Hello, Cody!


In [76]:
dogs = ['border collie', 'australian cattle dog', 'labrador retriever']

In [77]:
dogs = ['border collie', 'australian cattle dog', 'labrador retriever']
dog = dogs[0]
print(dog.title())

Border Collie


In [78]:
dogs = ['border collie', 'australian cattle dog', 'labrador retriever']
dog = dogs[-1]
print(dog.title())

Labrador Retriever


In [79]:
dogs = ['border collie', 'australian cattle dog', 'labrador retriever']
for dog in dogs:
    print(dog)

border collie
australian cattle dog
labrador retriever


In [80]:
dogs = ['border collie', 'australian cattle dog', 'labrador retriever']
print("Results for the dog show are as follows:\n")
for index, dog in enumerate(dogs):
    place = str(index)
    print(place + " - " + dog.title())

Results for the dog show are as follows:

0 - Border Collie
1 - Australian Cattle Dog
2 - Labrador Retriever


### Завдання 2 

### <center> Тема «Основи Python. Списки і словники»  <center>

Завдання 1

In [81]:
def print_list(colors_list):
    if not colors_list:
        print("No more colors")
    else:
        for ind, col in enumerate(colors_list):
            plc = str(ind)
            print(plc + " - " + col)

In [82]:
colors = ['blue', 'green']
print_list(colors)

0 - blue
1 - green


In [83]:
colors.index('blue')

0

In [84]:
colors.append('red')
colors.insert(0, 'white')
print_list(colors)

0 - white
1 - blue
2 - green
3 - red


In [85]:
colors.pop(-1)
colors.pop(1)
print_list(colors)

0 - white
1 - green


In [86]:
colors.remove('green')
colors.pop(0)
print_list(colors)

No more colors


Завдання 2

№ варіанта - 3

> Створіть словник для зберігання інформації про клієнта: прізвище, ім'я, дата народження, e-mail, стать, країна проживання, місто.
> Виведіть кожен фрагмент інформації, що зберігається в словнику.

In [87]:
def print_client(dct):
    for head, client_value in dct.items():
        print(f"{head.title()} - {client_value}")

In [88]:
client = {
    "name": "First Name",
    "surname": "Last Name",
    "year": "1.1.2000",
    "email": "test@gmail.com",
    "sex": "Male",
    "country": "United States",
    "city": "New York"
}

In [89]:
print_client(client)

Name - First Name
Surname - Last Name
Year - 1.1.2000
Email - test@gmail.com
Sex - Male
Country - United States
City - New York


In [90]:
N = 0

In [91]:
def get_clients():
    while True:
        num = input("Number of clients: ")
        try:
            test_client_list = int(num)
            if test_client_list > N:
                return test_client_list
            else:
                print("The number must be greater than zero")
        except ValueError:
            print("Invalid input")

In [92]:
client_list = []
num_clients = get_clients()
print(f"You entered: {num_clients}")

for i in range(1, num_clients + 1):
    t_dict = {}
    for key in client:
        t_dict[key] = input(f"Enter for client {i} {key.title()}: ")
    client_list.append(t_dict)

KeyboardInterrupt: Interrupted by user

In [34]:
for index, dct in enumerate(client_list, start=1):
    print(f"{index} client:", dct)

1 client: {'name': '1', 'surname': '1', 'year': '1', 'email': '1', 'sex': '1', 'country': '1', 'city': '1'}


Завдання 3

№ варіанта - 3

> Створіть Основний словник, який містить імена продавців iphone, і модель.
> Створіть додатковий словник, який містить назви моделейі ціну.
> Вивести імена тих продавців, які продають моделі старше 6 років зціною не більше $500, модель та ціну в порядку зменшення ціни.
> Якщо в додатковому словнику є моделі, які не продаються (відсутнів першому словнику), виведіть їх назви списком.

In [35]:
from datetime import datetime

In [36]:
seller_dict = {
    "Amazon": ["iPhone 12", "iPhone 14"],
    "Apple": ["iPhone 16", "iPhone 15"],
    "Walmart": ["iPhone 13", "iPhone 11"]
}
price_dict = {
    "iPhone 1": [2, 2000],
    "iPhone 11": [200, 2017],
    "iPhone 12": [440, 2018],
    "iPhone 13": [600, 2019],
    "iPhone 14": [710, 2020],
    "iPhone 15": [800, 2024],
    "iPhone 16": [900, 2025]
}

In [37]:
result = []
models = []
six_from_year = datetime.now().year - 6

for seller, stock in seller_dict.items():
    for model in stock:
        models.append(model)
        price, year = price_dict[model]
        if price <= 500 and year <= six_from_year:
            result.append((seller, model, price))

sorted_result = sorted(result, key=lambda x: x[2], reverse=True)

for seller, model, price in sorted_result:
    print(f"{seller}: {model} - ${price}")

old_models = []
for model in price_dict.keys():
    if model not in models:
        old_models.append(model)

print(old_models)

Amazon: iPhone 12 - $440
Walmart: iPhone 11 - $200
['iPhone 1']
