### Завдання 1

In [2]:
import numpy as np

In [3]:
a = 3
b = 6
c = 1
n = 1
m = 15


1.Створити вектор нульових значень (довжиною a)

In [4]:
v1 = np.zeros(a)
v1

array([0., 0., 0.])

2.Створити вектор нульових значень (довжиною b), змінити (b-4) елемент на значення с.

In [5]:
v2 = np.zeros(b)
v2

array([0., 0., 0., 0., 0., 0.])

In [6]:
v2[4] = c
v2

array([0., 0., 0., 0., 1., 0.])

3.Створити вектор із значеннями в діапазоні від n до m

In [7]:
v3 = np.arange(n,m)
v3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

4.Розгорнути вектор (перший елемент стає останнім)

In [8]:
v3 = v3[::-1]
v3

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

5.Зі списку L=[0,1,2,3,4,5,6,7,8] створити матрицю 3х3

In [9]:
L = np.array([0,1,2,3,4,5,6,7,8])
new_L = L.reshape(3,3)
new_L

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

6.Створити матрицю 2×3 зі значеннями в діапазоні від 0 до 5

In [10]:
arr = np.arange(6).reshape(2, 3)
print(arr)

[[0 1 2]
 [3 4 5]]


7.Створити матрицю a x b з 5 всередині та 1 на межах

In [11]:
a, b = 5, 4
matrix = np.ones((a, b), dtype=np.int64)
matrix[1:-1, 1:-1] = 5
print(matrix)


[[1 1 1 1]
 [1 5 5 1]
 [1 5 5 1]
 [1 5 5 1]
 [1 1 1 1]]


8.Сформувати зрізи для отримання зафарбованих елементів.

In [12]:
arr1 = np.array([2, 3, 6, 8, 11, 34])
print(arr1[2:4])

arr2 = np.array(
    (
        [2, 3, 6, 8, 11, 34],
        [11, 22, 3, 67, 11, 87],
        [3, 6, 3, 11, 89, 14],
        [4, 5, 8, 1, 4, 67],
    )
)
print(arr2[0:4, 1:3])
print(arr2[0::2, 0:])
print(arr2[:, [1, 3, 5]])
print(arr2[2, 0:3])
print(arr2[1:, 4:])


[6 8]
[[ 3  6]
 [22  3]
 [ 6  3]
 [ 5  8]]
[[ 2  3  6  8 11 34]
 [ 3  6  3 11 89 14]]
[[ 3  8 34]
 [22 67 87]
 [ 6 11 14]
 [ 5  1 67]]
[3 6 3]
[[11 87]
 [89 14]
 [ 4 67]]


### Завдання 2. Аналіз клієнтів оператора мобільного зв'язку

Задати рядок, що містить імена клієнтів,
а також інформацію про тривалість дзвінків цих клієнтів у роумінгу за кожен з
останніх 6 місяців; значення варіюються від 100 до 350 хв/міс.

In [13]:
C_names = "Barnes Bob Arthur John Clint Lewin"
arr_names = np.array(C_names.split())

1. Згенерувати масив NumPy «Customer’s roaming call duration», який міститиме цю інформацію, використавши відповідний метод модуля випадкових чисел.

In [14]:
from numpy.random import default_rng
rng = default_rng(2025)
call_duration = rng.integers(100, 350, size=(6,6), endpoint=True)
print(call_duration)

[[212 349 349 195 339 307]
 [260 310 292 344 196 119]
 [214 179 222 330 342 269]
 [259 171 103 197 214 157]
 [299 141 220 138 187 344]
 [267 206 155 115 321 223]]


In [15]:
for i, name in enumerate(arr_names):
    print(f"{name}: {call_duration[i]}")


Barnes: [212 349 349 195 339 307]
Bob: [260 310 292 344 196 119]
Arthur: [214 179 222 330 342 269]
John: [259 171 103 197 214 157]
Clint: [299 141 220 138 187 344]
Lewin: [267 206 155 115 321 223]


2. Вибрати (вивести) з нього всі рядки з інформацією про клієнтів John і
Clint.

In [23]:
wanted_2 = ["John", "Clint"]
mask = np.isin(arr_names, wanted_2)
sel = call_duration[mask]
sel

array([[171, 103, 197],
       [141, 220, 138]])

3. Вибрати відомості про всіх клієнтів, окрім Barnes і Bob.

In [22]:
wanted_3 = ["Barnes", "Bob"]
mask = ~np.isin(arr_names, wanted_3)
sel = call_duration[mask]
sel

array([[214, 179, 222, 330, 342, 269],
       [259, 171, 103, 197, 214, 157],
       [299, 141, 220, 138, 187, 344],
       [267, 206, 155, 115, 321, 223]])

4. Вивести інформацію про клієнта Bob за період 2–4 місяці.

In [30]:
wanted_4 = ["Bob"]
mask = np.isin(arr_names, wanted_4)
sel = call_duration[mask]
sel[:,1:4]

array([[310, 292, 344]])

5. Вивести інформацію про всіх клієнтів, окрім Barnes, за непарні місяці.

In [33]:
wanted_5 = ["Barnes"]
mask = ~np.isin(arr_names, wanted_5)
sel = call_duration[mask]
sel[:,0::2]

array([[260, 292, 196],
       [214, 222, 342],
       [259, 103, 214],
       [299, 220, 187],
       [267, 155, 321]])

6. Вартість хвилини розмови в роумінгу становить 1,6 $. Створити новий масив
NumPy «Customer’s roaming call cost», що міститиме витрати кожного клієнта в певному
місяці на основі даних з масиву «Customer’s roaming call duration».

7. Курс долара становить 40 ₴. Обчислити та вивести загальні витрати клієнта
Andrews у гривнях.

У завданнях 2, 3, 4, 6, 7 задати свої імена відповідно до створеного рядка та вартість
роумінгу.

### Завдання 3. Робота з модулем random, fancy indexing

Тривалість розмов клієнтів мобільного оператора в роумінгу за останні M місяців
варіюєтьсявід 1000 до 4000 хвилин.
Припустимо, у компанії обслуговується лише N абонентів.
Згенерувати NumPy, що містить інформацію про “Roaming call duration”,
використовуючивідповідний метод модуля random.
Використовуючи Fancy indexing вибрати підмножину у вказаному порядку,
представленомудвома 2 NumPy масивами:
i=[[2,4],[7,8]],
j=[[0,2],[9,6]]

<p> Варіант 3 </p>

In [217]:
N=31
M=62