<center> Практична робота №2 </center>
<center> з дисципліни «Аналіз даних з використанням Python» </center>
<center> на тему «Основи NumPy: робота з об'єктом ndarray, індексація NumPy масивів» </center>
<center> Варіант №3 </center>

<div style="margin-left: 80%;"> Виконав: </div>
<div style="margin-left: 80%;"> ст. гр. АС-227 </div>
<div style="margin-left: 80%;"> Бліняєв В.О. </div>
<div style="margin-left: 80%;"> Перевірила: </div>
<div style="margin-left: 80%;"> ст. в. Штефан Н.З. </div>


### Завдання 1

In [7]:
import numpy as np

In [8]:
a=3
b=6
c=1
n=1
m=15

1.Створити вектор нульових значень (довжиною a)

In [9]:
v1=np.zeros(a)
v1

array([0., 0., 0.])

2.Створити вектор нульових значень (довжиною b), змінити (b-4) елемент на значення с.

In [10]:
v2=np.zeros(b)
v2

array([0., 0., 0., 0., 0., 0.])

In [11]:
v2[4]=c
v2

array([0., 0., 0., 0., 1., 0.])

3.Створити вектор із значеннями в діапазоні від n до m

In [12]:
v3=np.arange(n,m)
v3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

4.Розгорнути вектор (перший елемент стає останнім)

In [13]:
v3=v3[::-1]
v3

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

5.Зі списку L=[0,1,2,3,4,5,6,7,8] створити матрицю 3х3

In [14]:
L=np.array([0,1,2,3,4,5,6,7,8])
new_L = L.reshape(3,3)
new_L

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

6.Створити матрицю 2×3 зі значеннями в діапазоні від 0 до 5

In [38]:
arr = np.arange(6).reshape(2, 3)
print(arr)

[[0 1 2]
 [3 4 5]]


7.Створити матрицю a x b з 5 всередині та 1 на межах

In [16]:
first_name = 'ada'
last_name = 'lovelace'
full_name = first_name + ' ' + last_name
print(full_name.title())

Ada Lovelace


8.Сформувати зрізи для отримання зафарбованих елементів.

In [40]:
arr1=[2,3,6,8,11,34]
arr2=([2,3,6,8,11,34],[11,22,3,67,11,87],[3,6,3,11,89,14],[4,5,8,1,4,67])


([2, 3, 6, 8, 11, 34], [11, 22, 3, 67, 11, 87], [3, 6, 3, 11, 89, 14], [4, 5, 8, 1, 4, 67])


### Завдання 2. Аналіз клієнтів оператора мобільного зв'язку

Задати рядок, що містить імена клієнтів, наприклад:
C_names = “Barnes Abramson Macduff Johnson Andrews Lewin Brown”,
а також інформацію про тривалість дзвінків цих клієнтів у роумінгу за кожен з
останніх 6 місяців; значення варіюються від 100 до 350 хв/міс.

In [18]:
def get_number_word(number):
    # Takes in a numerical value, and returns
    # the word corresponding to that number.
    if number == 0:
        return 'zero'
    elif number == 1:
        return 'one'
    elif number == 2:
        return 'two'
    elif number == 3:
        return 'three'
    return None


# Let's try out our function.
for current_number in range(0, 4):
    number_word = get_number_word(current_number)
    print(current_number, number_word)

0 zero
1 one
2 two
3 three


1. Згенерувати масив NumPy «Customer’s roaming call duration», який міститиме цю інформацію, використавши відповідний метод модуля випадкових чисел.

In [19]:
students = ['bernice', 'aaron', 'cody']
for student in students:
    print("Hello, " + student.title() + "!")

Hello, Bernice!
Hello, Aaron!
Hello, Cody!


2. Вибрати (вивести) з нього всі рядки з інформацією про клієнтів Abramson і
Johnson.

In [20]:
dogs = ['border collie', 'australian cattle dog', 'labrador retriever']
dog = dogs[0]
print(dog.title())

Border Collie


3. Вибрати відомості про всіх клієнтів, окрім Macduff і Lewin.

In [21]:
dogs = ['border collie', 'australian cattle dog', 'labrador retriever']
for dog in dogs:
    print(dog)

border collie
australian cattle dog
labrador retriever


4. Вивести інформацію про клієнта Brown за період 2–4 місяці.

5. Вивести інформацію про всіх клієнтів, окрім Barnes, за непарні місяці.

6. Вартість хвилини розмови в роумінгу становить 1,6 $. Створити новий масив
NumPy «Customer’s roaming call cost», що міститиме витрати кожного клієнта в певному
місяці на основі даних з масиву «Customer’s roaming call duration».

7. Курс долара становить 40 ₴. Обчислити та вивести загальні витрати клієнта
Andrews у гривнях.

У завданнях 2, 3, 4, 6, 7 задати свої імена відповідно до створеного рядка та вартість
роумінгу.

### Завдання 3. Робота з модулем random, fancy indexing

Тривалість розмов клієнтів мобільного оператора в роумінгу за останні M місяців
варіюєтьсявід 1000 до 4000 хвилин.
Припустимо, у компанії обслуговується лише N абонентів.
Згенерувати NumPy, що містить інформацію про “Roaming call duration”,
використовуючивідповідний метод модуля random.
Використовуючи Fancy indexing вибрати підмножину у вказаному порядку,
представленомудвома 2 NumPy масивами:
i=[[2,4],[7,8]],
j=[[0,2],[9,6]]

<p> Варіант 3 </p>
<p> N = 31 </p>
<p> M = 62 </p>

In [22]:
def print_client(dct):
    for head, client_value in dct.items():
        print(f"{head.title()} - {client_value}")

In [23]:
client = {
    "name": "First Name",
    "surname": "Last Name",
    "year": "1.1.2000",
    "email": "test@gmail.com",
    "sex": "Male",
    "country": "United States",
    "city": "New York"
}

In [24]:
print_client(client)

Name - First Name
Surname - Last Name
Year - 1.1.2000
Email - test@gmail.com
Sex - Male
Country - United States
City - New York


In [25]:
N = 0

In [26]:
def get_clients():
    while True:
        num = input("Number of clients: ")
        try:
            test_client_list = int(num)
            if test_client_list > N:
                return test_client_list
            else:
                print("The number must be greater than zero")
        except ValueError:
            print("Invalid input")

In [27]:
client_list = []
num_clients = get_clients()
print(f"You entered: {num_clients}")

for i in range(1, num_clients + 1):
    t_dict = {}
    for key in client:
        t_dict[key] = input(f"Enter for client {i} {key.title()}: ")
    client_list.append(t_dict)

KeyboardInterrupt: Interrupted by user

In [34]:
for index, dct in enumerate(client_list, start=1):
    print(f"{index} client:", dct)

1 client: {'name': '1', 'surname': '1', 'year': '1', 'email': '1', 'sex': '1', 'country': '1', 'city': '1'}


Завдання 3

№ варіанта - 3

> Створіть Основний словник, який містить імена продавців iphone, і модель.
> Створіть додатковий словник, який містить назви моделейі ціну.
> Вивести імена тих продавців, які продають моделі старше 6 років зціною не більше $500, модель та ціну в порядку зменшення ціни.
> Якщо в додатковому словнику є моделі, які не продаються (відсутнів першому словнику), виведіть їх назви списком.

In [35]:
from datetime import datetime

In [36]:
seller_dict = {
    "Amazon": ["iPhone 12", "iPhone 14"],
    "Apple": ["iPhone 16", "iPhone 15"],
    "Walmart": ["iPhone 13", "iPhone 11"]
}
price_dict = {
    "iPhone 1": [2, 2000],
    "iPhone 11": [200, 2017],
    "iPhone 12": [440, 2018],
    "iPhone 13": [600, 2019],
    "iPhone 14": [710, 2020],
    "iPhone 15": [800, 2024],
    "iPhone 16": [900, 2025]
}

In [37]:
result = []
models = []
six_from_year = datetime.now().year - 6

for seller, stock in seller_dict.items():
    for model in stock:
        models.append(model)
        price, year = price_dict[model]
        if price <= 500 and year <= six_from_year:
            result.append((seller, model, price))

sorted_result = sorted(result, key=lambda x: x[2], reverse=True)

for seller, model, price in sorted_result:
    print(f"{seller}: {model} - ${price}")

old_models = []
for model in price_dict.keys():
    if model not in models:
        old_models.append(model)

print(old_models)

Amazon: iPhone 12 - $440
Walmart: iPhone 11 - $200
['iPhone 1']
