1. № вар - 3
2. № конт. - 3
3. N1 - 11
4. N2 - 9
5. N3 - 13
6. M - 8
7. Місяці - червень, липень, серпень, вересень 2023, лютий, березень,
квітень, травень 2024

### <center> Контекст 3

Компанія продає товари на два ринки – Україна та Польща. Об’єкт аналізу – щомісячні обсяги експорту.

### Завдання 1

1. Створіть таблицю для України розміром N1×22 (N1 крамниця × 12 місяців 2023 року і перші 10
місяців 2024 року). Заповніть її цілими значеннями у діапазоні від 120 до 420 включно.

In [167]:
import numpy as np
rng = np.random.default_rng(42)

ukraine = np.array(rng.integers(120, 420, size=(11, 22), endpoint=True))
ukraine

array([[146, 352, 317, 252, 250, 378, 145, 329, 180, 148, 278, 413, 341,
        349, 335, 356, 274, 158, 372, 255, 270, 231],
       [174, 398, 355, 313, 241, 367, 284, 253, 255, 188, 147, 286, 387,
        139, 378, 369, 203, 310, 169, 348, 330, 226],
       [140, 412, 254, 388, 324, 354, 348, 178, 229, 260, 269, 133, 284,
        166, 343, 325, 397, 344, 230, 411, 243, 218],
       [392, 231, 142, 261, 359, 177, 259, 159, 326, 263, 219, 188, 289,
        321, 403, 251, 168, 370, 309, 330, 149, 214],
       [351, 370, 251, 362, 373, 236, 390, 206, 192, 325, 311, 162, 370,
        180, 362, 122, 359, 356, 354, 320, 261, 332],
       [203, 354, 287, 258, 272, 291, 131, 162, 193, 154, 252, 321, 316,
        261, 377, 290, 143, 350, 292, 311, 290, 286],
       [147, 288, 359, 211, 301, 129, 224, 251, 415, 184, 203, 242, 418,
        376, 130, 190, 367, 137, 377, 204, 396, 208],
       [250, 319, 158, 287, 272, 355, 419, 319, 243, 242, 245, 365, 216,
        170, 220, 126, 151, 147, 352, 

2. Створіть таблицю для Польщі розміром N2×22 (N2 крамниця × 12 місяців 2023 року і перші 10
місяців 2024 року). Заповніть її цілими значеннями у діапазоні від 90 до 300 включно.

In [168]:
poland = np.array(rng.integers(90, 300, size=(9, 22), endpoint=True))
poland

array([[109, 227, 222, 107, 249, 177, 256,  98, 127, 194, 129, 159, 229,
        120, 232, 111, 126, 213, 257, 125, 153, 285],
       [298, 212, 184, 163, 219, 214, 152,  94, 121, 292, 178, 191, 188,
        255, 103, 107, 148, 192, 231, 193, 183, 287],
       [123, 210, 204, 189, 260, 146, 291, 159, 204, 199, 269, 182, 150,
         94, 166, 264,  92, 279, 204, 119, 153, 206],
       [156, 112, 230, 231, 115, 149, 141, 229, 244, 243, 288, 252, 157,
        112, 219, 283, 295, 138, 139,  97, 119, 207],
       [205, 168, 155, 265, 187, 260, 293, 156, 132, 291, 223, 151, 221,
        198, 281, 144, 299, 287, 128, 124, 202,  99],
       [153, 181, 294, 299, 121, 278, 109, 247, 268, 277, 137, 278, 114,
        199, 189, 156,  94, 252, 160, 229, 176, 168],
       [277, 109, 245, 247, 170, 145,  91, 287, 289, 140,  96, 115, 104,
        265, 278, 122, 247, 127, 167, 216, 241, 274],
       [ 99, 131, 149, 155, 300, 254, 157, 295, 195, 195, 181, 120, 287,
         92, 126, 138, 148, 117,  93, 

3. Присвойте кожному супермаркету реалістичну назву. Місяці позначте українськими назвами.

In [169]:
ukraine_stores = [f"Україна_{i+1}" for i in range(ukraine.shape[0])]
poland_stores = [f"Польща_{i+1}" for i in range(poland.shape[0])]
store_names = np.concatenate((ukraine_stores, poland_stores))

months = [
    "Січень_23", "Лютий_23", "Березень_23", "Квітень_23", "Травень_23", "Червень_23",
    "Липень_23", "Серпень_23", "Вересень_23", "Жовтень_23", "Листопад_23", "Грудень_23",
    "Січень_24", "Лютий_24", "Березень_24", "Квітень_24", "Травень_24",
    "Червень_24", "Липень_24", "Серпень_24", "Вересень_24", "Жовтень_24"
]

### Завдання 2

Створіть одну спільну таблицю такого вигляду:
* рядки – усі крамниці обох країн (усього 20 рядків);
* стовпчики – місяці для аналізу: червень, липень, серпень, вересень 2023, лютий, березень, квітень, травень 2024.
<p> Для цього візьміть зі створених у п.1 таблиць відповідні колонки і поєднайте їх по рядках у зазначеному
порядку місяців.
Далі саме ця матриця використовуватиметься для аналізу.

In [170]:
months_needed = ["Червень_23", "Липень_23", "Серпень_23", "Вересень_23",
                  "Лютий_24", "Березень_24", "Квітень_24", "Травень_24"]
columns = [months.index(m) for m in months_needed]

ukraine_sel = ukraine[:, columns]
poland_sel = poland[:, columns]

combined = np.vstack((ukraine_sel, poland_sel))
combined

array([[378, 145, 329, 180, 349, 335, 356, 274],
       [367, 284, 253, 255, 139, 378, 369, 203],
       [354, 348, 178, 229, 166, 343, 325, 397],
       [177, 259, 159, 326, 321, 403, 251, 168],
       [236, 390, 206, 192, 180, 362, 122, 359],
       [291, 131, 162, 193, 261, 377, 290, 143],
       [129, 224, 251, 415, 376, 130, 190, 367],
       [355, 419, 319, 243, 170, 220, 126, 151],
       [165, 269, 329, 269, 210, 325, 309, 302],
       [330, 257, 200, 350, 335, 357, 255, 341],
       [212, 363, 294, 284, 348, 268, 336, 319],
       [177, 256,  98, 127, 120, 232, 111, 126],
       [214, 152,  94, 121, 255, 103, 107, 148],
       [146, 291, 159, 204,  94, 166, 264,  92],
       [149, 141, 229, 244, 112, 219, 283, 295],
       [260, 293, 156, 132, 198, 281, 144, 299],
       [278, 109, 247, 268, 199, 189, 156,  94],
       [145,  91, 287, 289, 265, 278, 122, 247],
       [254, 157, 295, 195,  92, 126, 138, 148],
       [212, 177, 132, 272, 245, 264, 117, 181]])

### Завдання 3

1. Для кожного з М місяців обчисліть: суму, найбільше та найменше значення обсягів експорту
(по всіх крамницях).

3. Результати подайте окремо:
* вектор із M сум;
* вектор із M найбільших значень та відповідних їм місяців і обʼєктів;
* вектор із M найменших значень та відповідних їм місяців і обʼєктів;
* вектор із N1+N2 середнього (по кожному обʼєкту).

In [171]:
sum_by_month = combined.sum(0)
sum_by_month

array([4829, 4756, 4377, 4788, 4435, 5356, 4371, 4654])

In [172]:
max_values = combined.max(axis=0)
max_indices = combined.argmax(axis=0)

for m_idx, (val, s_idx) in enumerate(zip(max_values, max_indices)):
    print(f"{months_needed[m_idx]}: {store_names[s_idx]} - {val}")

Червень_23: Україна_1 - 378
Липень_23: Україна_8 - 419
Серпень_23: Україна_1 - 329
Вересень_23: Україна_7 - 415
Лютий_24: Україна_7 - 376
Березень_24: Україна_4 - 403
Квітень_24: Україна_2 - 369
Травень_24: Україна_3 - 397


In [173]:
min_values = combined.min(axis=0)
min_indices = combined.argmin(axis=0)

for m_idx, (val, s_idx) in enumerate(zip(min_values, min_indices)):
    print(f"{months_needed[m_idx]}: {store_names[s_idx]} - {val}")

Червень_23: Україна_7 - 129
Липень_23: Польща_7 - 91
Серпень_23: Польща_2 - 94
Вересень_23: Польща_2 - 121
Лютий_24: Польща_8 - 92
Березень_24: Польща_2 - 103
Квітень_24: Польща_2 - 107
Травень_24: Польща_3 - 92


2. Для кожного обʼєкта обчисліть середній обсяг експорту за ці М місяців.

In [174]:
mean_by_month = combined.mean(axis=1)
for i, name in enumerate(store_names):
    print(f"{name}: {mean_by_month[i]}")

Україна_1: 293.25
Україна_2: 281.0
Україна_3: 292.5
Україна_4: 258.0
Україна_5: 255.875
Україна_6: 231.0
Україна_7: 260.25
Україна_8: 250.375
Україна_9: 272.25
Україна_10: 303.125
Україна_11: 303.0
Польща_1: 155.875
Польща_2: 149.25
Польща_3: 177.0
Польща_4: 209.0
Польща_5: 220.375
Польща_6: 192.5
Польща_7: 215.5
Польща_8: 175.625
Польща_9: 200.0


### Завдання 4

Обчисліть загальний обсяг експорту за останні два місяці у спільній таблиці з п.2, підсумувавши всі
обʼєкти.

In [175]:
total_last2 = combined[:, -2:].sum()
total_last2

np.int64(9025)

### Завдання 5

1. Створіть таблицю для N3 нових обʼєктів розміром N3×24, що містить щомісячні обсяги
експорту за повні 24 місяці: січень–грудень 2023 та січень–грудень 2024.
2. Заповніть комірки реалістичними цілими значеннями у діапазоні від 80 до 500 включно там,
де експорт є.
3. Для місяців, у яких продажі відсутні, поставте nan.
4. Призначте осмислені назви кожному з N3 нових обʼєктів, а для стовпців використайте
українські назви місяців з роком.


In [176]:
full_months = [
    "Січень_23", "Лютий_23", "Березень_23", "Квітень_23", "Травень_23", "Червень_23",
    "Липень_23", "Серпень_23", "Вересень_23", "Жовтень_23", "Листопад_23", "Грудень_23",
    "Січень_24", "Лютий_24", "Березень_24", "Квітень_24", "Травень_24", "Червень_24",
    "Липень_24", "Серпень_24", "Вересень_24", "Жовтень_24", "Листопад_24", "Грудень_24"
]

In [177]:
real_store_names = np.array([f"Обʼєкт_{i+1}" for i in range(13)])

In [178]:
new_stores = rng.integers(80, 500, size=(13, 24), endpoint=True).astype(float)
mask = rng.random(size=new_stores.shape) < 0.1
new_stores[mask] = np.nan

print(f"{'':<15}", " ".join([f"{m:<12}" for m in months[:8]]))
for name, row in zip(real_store_names, new_stores):
    print(f"{name:<15}", " ".join([f"{x:<12}" for x in row[:8]]))

                Січень_23    Лютий_23     Березень_23  Квітень_23   Травень_23   Червень_23   Липень_23    Серпень_23  
Обʼєкт_1        489.0        206.0        135.0        285.0        294.0        359.0        212.0        482.0       
Обʼєкт_2        82.0         486.0        149.0        330.0        156.0        472.0        390.0        418.0       
Обʼєкт_3        402.0        335.0        472.0        445.0        nan          333.0        202.0        253.0       
Обʼєкт_4        nan          423.0        nan          124.0        451.0        108.0        nan          330.0       
Обʼєкт_5        271.0        128.0        307.0        88.0         378.0        103.0        162.0        153.0       
Обʼєкт_6        305.0        98.0         287.0        156.0        454.0        179.0        176.0        184.0       
Обʼєкт_7        250.0        469.0        370.0        121.0        432.0        435.0        417.0        460.0       
Обʼєкт_8        487.0        441.0      

### Завдання 6

5. Побудуйте єдину 24-місячну шкалу від січня 2023 до грудня 2024 (24 стовпчики у
фіксованому порядку).
6. Розширте вихідні таблиці з п. 1 до 24 стовпчиків. У стовпчиках, де дані відсутні, поставте nan.
7. Об’єднайте по рядках: N1 обʼєктів України, N2 обʼєктів Польщі (24 стовпчики), N3 нових
обʼєктів із п. 5. У підсумку отримаєте розширену 24-місячну таблицю розміром
(N1+N2+N3)×24.
8. Зафіксуйте правила інтерпретації nan у подальших розрахунках: для агрегувань «по місяцях» і «по обʼєктах» ігноруйте nan (обчислюйте по наявних значеннях);

In [179]:
ukraine_ext = np.hstack((ukraine, np.full((11, 2), np.nan)))
poland_ext  = np.hstack((poland,  np.full((9, 2), np.nan)))

combined_all = np.vstack((ukraine_ext, poland_ext, new_stores))
store_names   = np.concatenate((ukraine_stores, poland_stores, real_store_names))

combined_all

array([[ 146.000,  352.000,  317.000,  252.000,  250.000,  378.000,
         145.000,  329.000,  180.000,  148.000,  278.000,  413.000,
         341.000,  349.000,  335.000,  356.000,  274.000,  158.000,
         372.000,  255.000,  270.000,  231.000,  nan,  nan],
       [ 174.000,  398.000,  355.000,  313.000,  241.000,  367.000,
         284.000,  253.000,  255.000,  188.000,  147.000,  286.000,
         387.000,  139.000,  378.000,  369.000,  203.000,  310.000,
         169.000,  348.000,  330.000,  226.000,  nan,  nan],
       [ 140.000,  412.000,  254.000,  388.000,  324.000,  354.000,
         348.000,  178.000,  229.000,  260.000,  269.000,  133.000,
         284.000,  166.000,  343.000,  325.000,  397.000,  344.000,
         230.000,  411.000,  243.000,  218.000,  nan,  nan],
       [ 392.000,  231.000,  142.000,  261.000,  359.000,  177.000,
         259.000,  159.000,  326.000,  263.000,  219.000,  188.000,
         289.000,  321.000,  403.000,  251.000,  168.000,  370.000,
 

### Завдання 7

Знайдіть:
* один найбільший показник експорту у всій таблиці (значення, назва обʼєкту, назва місяця);
* один найменший показник (значення, назва обʼєкту, назва місяця).
<p> Подайте результат у двох окремих реченнях із чіткими назвами обʼєкту та місяця.

In [180]:
max_value = np.nanmax(combined_all)
min_value = np.nanmin(combined_all)

max_pos = np.where(combined_all == max_value)
min_pos = np.where(combined_all == min_value)

print(f"Найбільший показник експорту: {max_value} - {store_names[int(max_pos[0][0])]} - {full_months[int(max_pos[1][0])]}\n")
print(f"Найменший показник експорту: {min_value} - {store_names[int(min_pos[0][0])]} - {full_months[int(min_pos[1][0])]}")

Найбільший показник експорту: 499.0 - Обʼєкт_11 - Листопад_23

Найменший показник експорту: 82.0 - Обʼєкт_2 - Січень_23


### Завдання 8

Для кожного з M місяців розширеної таблиці:


4. обчисліть середній місячний показник експорту по всіх обʼєктах;


In [181]:
np.set_printoptions(formatter={'float': '{: 0.3f}'.format})

In [182]:
mean_by_month = np.nanmean(combined_all, axis=0)
print(mean_by_month)

[ 245.094  275.303  274.000  250.355  283.719  265.182  245.419  261.848
  260.152  253.688  263.839  283.250  263.516  237.879  286.800  237.424
  254.931  265.818  274.967  230.182  247.485  235.226  351.273  270.100]


5. обчисліть вибіркове стандартне відхилення (із дільником n–1);


In [183]:
std_by_month = np.nanstd(combined_all, axis=0, ddof=1)
std_by_month

array([ 114.055,  115.565,  100.785,  89.971,  101.594,  103.896,
        102.917,  106.007,  85.054,  95.313,  115.697,  111.546,  109.203,
        109.372,  111.597,  94.569,  114.531,  108.248,  107.416,  96.983,
        91.843,  90.254,  105.430,  134.159])

6. сформулюйте речення у вигляді: «У середньому у [назва місяця] 2024 року обʼєкти мережі експортували M ± S одиниць».

In [189]:
for month, mean_val, std_val in zip(full_months, mean_by_month, std_by_month):
    if month.endswith("_24"):
        print(f"У середньому у {month} обʼєкти мережі експортували {round(std_val, 2)} ± {round(std_val, 2)} одиниць")

У середньому у Січень_24 обʼєкти мережі експортували 109.2 ± 109.2 одиниць
У середньому у Лютий_24 обʼєкти мережі експортували 109.37 ± 109.37 одиниць
У середньому у Березень_24 обʼєкти мережі експортували 111.6 ± 111.6 одиниць
У середньому у Квітень_24 обʼєкти мережі експортували 94.57 ± 94.57 одиниць
У середньому у Травень_24 обʼєкти мережі експортували 114.53 ± 114.53 одиниць
У середньому у Червень_24 обʼєкти мережі експортували 108.25 ± 108.25 одиниць
У середньому у Липень_24 обʼєкти мережі експортували 107.42 ± 107.42 одиниць
У середньому у Серпень_24 обʼєкти мережі експортували 96.98 ± 96.98 одиниць
У середньому у Вересень_24 обʼєкти мережі експортували 91.84 ± 91.84 одиниць
У середньому у Жовтень_24 обʼєкти мережі експортували 90.25 ± 90.25 одиниць
У середньому у Листопад_24 обʼєкти мережі експортували 105.43 ± 105.43 одиниць
У середньому у Грудень_24 обʼєкти мережі експортували 134.16 ± 134.16 одиниць


### Завдання 9

1. Для кожного з M місяців визначте значення L, нижче якого лежить 60% показника експорту
серед усіх обʼєктів (поріг по місяцях).

In [185]:
L_by_month = np.percentile(combined_6_8_ext, 60, axis=0)
L_by_city = np.percentile(combined_6_8_ext, 60, axis=1)
print("L по місяцях:", L_by_month)
print("L по регіонах:", L_by_city)

NameError: name 'combined_6_8_ext' is not defined

2. Для кожного обʼєкту визначте значення L, нижче якого лежить 60% його власних місячних
показників експорту у межах цих M місяців (поріг по обʼєктах).

In [ ]:
L_by_month = np.percentile(combined_6_8_ext, 60, axis=0)
L_by_city = np.percentile(combined_6_8_ext, 60, axis=1)
print("L по місяцях:", L_by_month)
print("L по регіонах:", L_by_city)

### Завдання 10

Для кожного з M місяців розширеної таблиці:

1. знайдіть значення, що відповідає 95-му процентилю;


2. створіть копію таблиці та замініть кожен елемент, що перевищує порогове значення, на саме
це порогове значення;

3. збережіть усі інші елементи без змін.
Додатково порівняйте підсумки по місяцях «до» та «після» такого обрізання.

2. створіть копію таблиці та замініть кожен елемент, що перевищує порогове значення, на саме
це порогове значення;### Завдання 11

Для кожного обʼєкту в розширеній таблиці обчисліть послідовність ковзної середньої з вікном 3 місяці
для таких чотирьох вікон:
* квітень–травень–червень 2024,
* травень–червень–серпень 2024,
* червень–серпень–вересень 2024,
* серпень–вересень–жовтень 2024.
<p> Подайте результат у вигляді нової таблиці з чотирма стовпчиками (по одному для кожного
вікна).

### Завдання 12

Для кожного з M місяців (див. таблицю варіантів):

1. нормуйте замовлення по обʼєктах за цим місяцем, віднімаючи середнє і ділячи на стандартне
відхилення (вибіркове);

2. позначте ті комірки, де модуль нормованого значення перевищує 2;


3. підрахуйте, скільки таких випадків у кожному місяці та які це обʼєкти.

2. позначте ті комірки, де модуль нормованого значення перевищує 2;
### Завдання 13

Задайте вектор відсотків очікуваного приросту експорту для M місяців у такому порядку: [3%, 5%,
2%, 0%, 1%, 4%, 2%, 1%] (відповідно для заданих у таблиці варіантів місяців).
<p> Застосуйте ці коефіцієнти до кожного елемента розширеної таблиці (помножте на 1 +коефіцієнт) та
сформуйте таблицю прогнозу експорту.

### Завдання 14

Для розширеної таблиці з M місяців (див. таблицю варіантів):

1. для кожного обʼєкту обчисліть сумарний експорт за всі M місяців;

2. відсортуйте обʼєкти за спаданням цієї суми;

3. випишіть п’ять обʼєктів із найбільшим сумарним експортом, зазначивши назви та значення
сум.

### Завдання 15

1. Випадковим чином замініть 5% елементів розширеної таблиці на позначку «немає даних».

2. Для кожного з M місяців обчисліть середній експорт, ігноруючи комірки з позначкою «немає
даних».

3. Додатково порахуйте частку пропусків у кожному місяці (скільки відсотків комірок позначено
як «немає даних»).