1. № вар - 3
2. № конт. - 3
3. N1 - 11
4. N2 - 9
5. N3 - 13
6. M - 8
7. Місяці - червень, липень, серпень, вересень 2023, лютий, березень,
квітень, травень 2024

### <center> Контекст 3

Компанія продає товари на два ринки – Україна та Польща. Об’єкт аналізу – щомісячні обсяги експорту.

### Завдання 1

1. Створіть таблицю для України розміром N1×22 (N1 крамниця × 12 місяців 2023 року і перші 10
місяців 2024 року). Заповніть її цілими значеннями у діапазоні від 120 до 420 включно.

In [603]:
import numpy as np
rng = np.random.default_rng(42)

ukraine = np.array(rng.integers(120, 420, size=(11, 22), endpoint=True))
ukraine

array([[146, 352, 317, 252, 250, 378, 145, 329, 180, 148, 278, 413, 341,
        349, 335, 356, 274, 158, 372, 255, 270, 231],
       [174, 398, 355, 313, 241, 367, 284, 253, 255, 188, 147, 286, 387,
        139, 378, 369, 203, 310, 169, 348, 330, 226],
       [140, 412, 254, 388, 324, 354, 348, 178, 229, 260, 269, 133, 284,
        166, 343, 325, 397, 344, 230, 411, 243, 218],
       [392, 231, 142, 261, 359, 177, 259, 159, 326, 263, 219, 188, 289,
        321, 403, 251, 168, 370, 309, 330, 149, 214],
       [351, 370, 251, 362, 373, 236, 390, 206, 192, 325, 311, 162, 370,
        180, 362, 122, 359, 356, 354, 320, 261, 332],
       [203, 354, 287, 258, 272, 291, 131, 162, 193, 154, 252, 321, 316,
        261, 377, 290, 143, 350, 292, 311, 290, 286],
       [147, 288, 359, 211, 301, 129, 224, 251, 415, 184, 203, 242, 418,
        376, 130, 190, 367, 137, 377, 204, 396, 208],
       [250, 319, 158, 287, 272, 355, 419, 319, 243, 242, 245, 365, 216,
        170, 220, 126, 151, 147, 352, 

2. Створіть таблицю для Польщі розміром N2×22 (N2 крамниця × 12 місяців 2023 року і перші 10
місяців 2024 року). Заповніть її цілими значеннями у діапазоні від 90 до 300 включно.

In [604]:
poland = np.array(rng.integers(90, 300, size=(9, 22), endpoint=True))
poland

array([[109, 227, 222, 107, 249, 177, 256,  98, 127, 194, 129, 159, 229,
        120, 232, 111, 126, 213, 257, 125, 153, 285],
       [298, 212, 184, 163, 219, 214, 152,  94, 121, 292, 178, 191, 188,
        255, 103, 107, 148, 192, 231, 193, 183, 287],
       [123, 210, 204, 189, 260, 146, 291, 159, 204, 199, 269, 182, 150,
         94, 166, 264,  92, 279, 204, 119, 153, 206],
       [156, 112, 230, 231, 115, 149, 141, 229, 244, 243, 288, 252, 157,
        112, 219, 283, 295, 138, 139,  97, 119, 207],
       [205, 168, 155, 265, 187, 260, 293, 156, 132, 291, 223, 151, 221,
        198, 281, 144, 299, 287, 128, 124, 202,  99],
       [153, 181, 294, 299, 121, 278, 109, 247, 268, 277, 137, 278, 114,
        199, 189, 156,  94, 252, 160, 229, 176, 168],
       [277, 109, 245, 247, 170, 145,  91, 287, 289, 140,  96, 115, 104,
        265, 278, 122, 247, 127, 167, 216, 241, 274],
       [ 99, 131, 149, 155, 300, 254, 157, 295, 195, 195, 181, 120, 287,
         92, 126, 138, 148, 117,  93, 

3. Присвойте кожному супермаркету реалістичну назву. Місяці позначте українськими назвами.

In [605]:
ukraine_stores = [f"Україна_{i+1}" for i in range(ukraine.shape[0])]
poland_stores = [f"Польща_{i+1}" for i in range(poland.shape[0])]
store_names = np.concatenate((ukraine_stores, poland_stores))

months = [
    "Січень_23", "Лютий_23", "Березень_23", "Квітень_23", "Травень_23", "Червень_23",
    "Липень_23", "Серпень_23", "Вересень_23", "Жовтень_23", "Листопад_23", "Грудень_23",
    "Січень_24", "Лютий_24", "Березень_24", "Квітень_24", "Травень_24",
    "Червень_24", "Липень_24", "Серпень_24", "Вересень_24", "Жовтень_24"
]

### Завдання 2

Створіть одну спільну таблицю такого вигляду:
* рядки – усі крамниці обох країн (усього 20 рядків);
* стовпчики – місяці для аналізу: червень, липень, серпень, вересень 2023, лютий, березень, квітень, травень 2024.
<p> Для цього візьміть зі створених у п.1 таблиць відповідні колонки і поєднайте їх по рядках у зазначеному
порядку місяців.
Далі саме ця матриця використовуватиметься для аналізу.

In [606]:
months_needed = ["Червень_23", "Липень_23", "Серпень_23", "Вересень_23",
                  "Лютий_24", "Березень_24", "Квітень_24", "Травень_24"]
columns = [months.index(m) for m in months_needed]

ukraine_sel = ukraine[:, columns]
poland_sel = poland[:, columns]

combined = np.vstack((ukraine_sel, poland_sel))
combined

array([[378, 145, 329, 180, 349, 335, 356, 274],
       [367, 284, 253, 255, 139, 378, 369, 203],
       [354, 348, 178, 229, 166, 343, 325, 397],
       [177, 259, 159, 326, 321, 403, 251, 168],
       [236, 390, 206, 192, 180, 362, 122, 359],
       [291, 131, 162, 193, 261, 377, 290, 143],
       [129, 224, 251, 415, 376, 130, 190, 367],
       [355, 419, 319, 243, 170, 220, 126, 151],
       [165, 269, 329, 269, 210, 325, 309, 302],
       [330, 257, 200, 350, 335, 357, 255, 341],
       [212, 363, 294, 284, 348, 268, 336, 319],
       [177, 256,  98, 127, 120, 232, 111, 126],
       [214, 152,  94, 121, 255, 103, 107, 148],
       [146, 291, 159, 204,  94, 166, 264,  92],
       [149, 141, 229, 244, 112, 219, 283, 295],
       [260, 293, 156, 132, 198, 281, 144, 299],
       [278, 109, 247, 268, 199, 189, 156,  94],
       [145,  91, 287, 289, 265, 278, 122, 247],
       [254, 157, 295, 195,  92, 126, 138, 148],
       [212, 177, 132, 272, 245, 264, 117, 181]])

### Завдання 3

1. Для кожного з М місяців обчисліть: суму, найбільше та найменше значення обсягів експорту
(по всіх крамницях).

3. Результати подайте окремо:
* вектор із M сум;
* вектор із M найбільших значень та відповідних їм місяців і обʼєктів;
* вектор із M найменших значень та відповідних їм місяців і обʼєктів;
* вектор із N1+N2 середнього (по кожному обʼєкту).

In [607]:
sum_by_month = combined.sum(0)
sum_by_month

array([4829, 4756, 4377, 4788, 4435, 5356, 4371, 4654])

In [608]:
max_values = combined.max(axis=0)
max_indices = combined.argmax(axis=0)

for m_idx, (val, s_idx) in enumerate(zip(max_values, max_indices)):
    print(f"{months_needed[m_idx]}: {store_names[s_idx]} - {val}")

Червень_23: Україна_1 - 378
Липень_23: Україна_8 - 419
Серпень_23: Україна_1 - 329
Вересень_23: Україна_7 - 415
Лютий_24: Україна_7 - 376
Березень_24: Україна_4 - 403
Квітень_24: Україна_2 - 369
Травень_24: Україна_3 - 397


In [609]:
min_values = combined.min(axis=0)
min_indices = combined.argmin(axis=0)

for m_idx, (val, s_idx) in enumerate(zip(min_values, min_indices)):
    print(f"{months_needed[m_idx]}: {store_names[s_idx]} - {val}")

Червень_23: Україна_7 - 129
Липень_23: Польща_7 - 91
Серпень_23: Польща_2 - 94
Вересень_23: Польща_2 - 121
Лютий_24: Польща_8 - 92
Березень_24: Польща_2 - 103
Квітень_24: Польща_2 - 107
Травень_24: Польща_3 - 92


2. Для кожного обʼєкта обчисліть середній обсяг експорту за ці М місяців.

In [610]:
mean_by_month = combined.mean(axis=1)
for i, name in enumerate(store_names):
    print(f"{name}: {mean_by_month[i]}")

Україна_1: 293.25
Україна_2: 281.0
Україна_3: 292.5
Україна_4: 258.0
Україна_5: 255.875
Україна_6: 231.0
Україна_7: 260.25
Україна_8: 250.375
Україна_9: 272.25
Україна_10: 303.125
Україна_11: 303.0
Польща_1: 155.875
Польща_2: 149.25
Польща_3: 177.0
Польща_4: 209.0
Польща_5: 220.375
Польща_6: 192.5
Польща_7: 215.5
Польща_8: 175.625
Польща_9: 200.0


### Завдання 4

Обчисліть загальний обсяг експорту за останні два місяці у спільній таблиці з п.2, підсумувавши всі
обʼєкти.

In [611]:
total_last2 = combined[:, -2:].sum()
total_last2

np.int64(9025)

### Завдання 5

1. Створіть таблицю для N3 нових обʼєктів розміром N3×24, що містить щомісячні обсяги
експорту за повні 24 місяці: січень–грудень 2023 та січень–грудень 2024.
2. Заповніть комірки реалістичними цілими значеннями у діапазоні від 80 до 500 включно там,
де експорт є.
3. Для місяців, у яких продажі відсутні, поставте nan.
4. Призначте осмислені назви кожному з N3 нових обʼєктів, а для стовпців використайте
українські назви місяців з роком.


In [612]:
full_months = ["Січень_23", "Лютий_23", "Березень_23", "Квітень_23", "Травень_23", "Червень_23", "Липень_23", "Серпень_23", "Вересень_23", "Жовтень_23", "Листопад_23", "Грудень_23", "Січень_24", "Лютий_24", "Березень_24", "Квітень_24", "Травень_24", "Червень_24", "Липень_24", "Серпень_24", "Вересень_24", "Жовтень_24", "Листопад_24", "Грудень_24"]

In [613]:
real_store_names = np.array([f"Обʼєкт_{i+1}" for i in range(13)])

In [614]:
new_stores = rng.integers(80, 500, size=(13, 24), endpoint=True).astype(float)
mask = rng.random(size=new_stores.shape) < 0.1
new_stores[mask] = np.nan

print(f"{'':<15}", " ".join([f"{m:<12}" for m in full_months[:8]]))
for name, row in zip(real_store_names, new_stores):
    print(f"{name:<15}", " ".join([f"{x:<12}" for x in row[:8]]))

                Січень_23    Лютий_23     Березень_23  Квітень_23   Травень_23   Червень_23   Липень_23    Серпень_23  
Обʼєкт_1        489.0        206.0        135.0        285.0        294.0        359.0        212.0        482.0       
Обʼєкт_2        82.0         486.0        149.0        330.0        156.0        472.0        390.0        418.0       
Обʼєкт_3        402.0        335.0        472.0        445.0        nan          333.0        202.0        253.0       
Обʼєкт_4        nan          423.0        nan          124.0        451.0        108.0        nan          330.0       
Обʼєкт_5        271.0        128.0        307.0        88.0         378.0        103.0        162.0        153.0       
Обʼєкт_6        305.0        98.0         287.0        156.0        454.0        179.0        176.0        184.0       
Обʼєкт_7        250.0        469.0        370.0        121.0        432.0        435.0        417.0        460.0       
Обʼєкт_8        487.0        441.0      

### Завдання 6

5. Побудуйте єдину 24-місячну шкалу від січня 2023 до грудня 2024 (24 стовпчики у
фіксованому порядку).
6. Розширте вихідні таблиці з п. 1 до 24 стовпчиків. У стовпчиках, де дані відсутні, поставте nan.
7. Об’єднайте по рядках: N1 обʼєктів України, N2 обʼєктів Польщі (24 стовпчики), N3 нових
обʼєктів із п. 5. У підсумку отримаєте розширену 24-місячну таблицю розміром
(N1+N2+N3)×24.
8. Зафіксуйте правила інтерпретації nan у подальших розрахунках: для агрегувань «по місяцях» і «по обʼєктах» ігноруйте nan (обчислюйте по наявних значеннях);

In [615]:
ukraine_ext = np.hstack((ukraine, np.full((11, 2), np.nan)))
poland_ext  = np.hstack((poland,  np.full((9, 2), np.nan)))

combined_all = np.vstack((ukraine_ext, poland_ext, new_stores))
store_names   = np.concatenate((ukraine_stores, poland_stores, real_store_names))

combined_all

array([[ 146.000,  352.000,  317.000,  252.000,  250.000,  378.000,
         145.000,  329.000,  180.000,  148.000,  278.000,  413.000,
         341.000,  349.000,  335.000,  356.000,  274.000,  158.000,
         372.000,  255.000,  270.000,  231.000,  nan,  nan],
       [ 174.000,  398.000,  355.000,  313.000,  241.000,  367.000,
         284.000,  253.000,  255.000,  188.000,  147.000,  286.000,
         387.000,  139.000,  378.000,  369.000,  203.000,  310.000,
         169.000,  348.000,  330.000,  226.000,  nan,  nan],
       [ 140.000,  412.000,  254.000,  388.000,  324.000,  354.000,
         348.000,  178.000,  229.000,  260.000,  269.000,  133.000,
         284.000,  166.000,  343.000,  325.000,  397.000,  344.000,
         230.000,  411.000,  243.000,  218.000,  nan,  nan],
       [ 392.000,  231.000,  142.000,  261.000,  359.000,  177.000,
         259.000,  159.000,  326.000,  263.000,  219.000,  188.000,
         289.000,  321.000,  403.000,  251.000,  168.000,  370.000,
 

### Завдання 7

Знайдіть:
* один найбільший показник експорту у всій таблиці (значення, назва обʼєкту, назва місяця);
* один найменший показник (значення, назва обʼєкту, назва місяця).
<p> Подайте результат у двох окремих реченнях із чіткими назвами обʼєкту та місяця.

In [616]:
max_value = np.nanmax(combined_all)
min_value = np.nanmin(combined_all)

max_pos = np.where(combined_all == max_value)
min_pos = np.where(combined_all == min_value)

print(f"Найбільший показник експорту: {max_value} - {store_names[int(max_pos[0][0])]} - {full_months[int(max_pos[1][0])]}\n")
print(f"Найменший показник експорту: {min_value} - {store_names[int(min_pos[0][0])]} - {full_months[int(min_pos[1][0])]}")

Найбільший показник експорту: 499.0 - Обʼєкт_11 - Листопад_23

Найменший показник експорту: 82.0 - Обʼєкт_2 - Січень_23


### Завдання 8

Для кожного з M місяців розширеної таблиці:


4. обчисліть середній місячний показник експорту по всіх обʼєктах;


In [617]:
np.set_printoptions(formatter={'float': '{: 0.3f}'.format})

In [618]:
mean_by_month = np.nanmean(combined_all, axis=0)
print(mean_by_month)

[ 245.094  275.303  274.000  250.355  283.719  265.182  245.419  261.848
  260.152  253.688  263.839  283.250  263.516  237.879  286.800  237.424
  254.931  265.818  274.967  230.182  247.485  235.226  351.273  270.100]


5. обчисліть вибіркове стандартне відхилення (із дільником n–1);


In [619]:
std_by_month = np.nanstd(combined_all, axis=0, ddof=1)
std_by_month

array([ 114.055,  115.565,  100.785,  89.971,  101.594,  103.896,
        102.917,  106.007,  85.054,  95.313,  115.697,  111.546,  109.203,
        109.372,  111.597,  94.569,  114.531,  108.248,  107.416,  96.983,
        91.843,  90.254,  105.430,  134.159])

6. сформулюйте речення у вигляді: «У середньому у [назва місяця] 2024 року обʼєкти мережі експортували M ± S одиниць».

In [620]:
for month, mean_val, std_val in zip(full_months, mean_by_month, std_by_month):
    if month.endswith("_24"):
        print(f"У середньому у {month} обʼєкти мережі експортували {round(std_val, 2)} ± {round(std_val, 2)} одиниць")

У середньому у Січень_24 обʼєкти мережі експортували 109.2 ± 109.2 одиниць
У середньому у Лютий_24 обʼєкти мережі експортували 109.37 ± 109.37 одиниць
У середньому у Березень_24 обʼєкти мережі експортували 111.6 ± 111.6 одиниць
У середньому у Квітень_24 обʼєкти мережі експортували 94.57 ± 94.57 одиниць
У середньому у Травень_24 обʼєкти мережі експортували 114.53 ± 114.53 одиниць
У середньому у Червень_24 обʼєкти мережі експортували 108.25 ± 108.25 одиниць
У середньому у Липень_24 обʼєкти мережі експортували 107.42 ± 107.42 одиниць
У середньому у Серпень_24 обʼєкти мережі експортували 96.98 ± 96.98 одиниць
У середньому у Вересень_24 обʼєкти мережі експортували 91.84 ± 91.84 одиниць
У середньому у Жовтень_24 обʼєкти мережі експортували 90.25 ± 90.25 одиниць
У середньому у Листопад_24 обʼєкти мережі експортували 105.43 ± 105.43 одиниць
У середньому у Грудень_24 обʼєкти мережі експортували 134.16 ± 134.16 одиниць


### Завдання 9

1. Для кожного з M місяців визначте значення L, нижче якого лежить 60% показника експорту
серед усіх обʼєктів (поріг по місяцях).

In [621]:
L_by_month = np.nanpercentile(combined_all, 60, axis=0)
for m, L in zip(full_months, L_by_month):
    print(f"{m}: {L:.2f}")

Січень_23: 267.40
Лютий_23: 322.20
Березень_23: 289.80
Квітень_23: 265.00
Травень_23: 297.60
Червень_23: 280.60
Липень_23: 259.00
Серпень_23: 294.20
Вересень_23: 269.60
Жовтень_23: 259.60
Листопад_23: 269.00
Грудень_23: 307.00
Січень_24: 289.00
Лютий_24: 261.80
Березень_24: 332.60
Квітень_24: 267.80
Травень_24: 298.20
Червень_24: 289.60
Липень_24: 305.40
Серпень_24: 238.20
Вересень_24: 270.80
Жовтень_24: 234.00
Листопад_24: 390.00
Грудень_24: 299.20


2. Для кожного обʼєкту визначте значення L, нижче якого лежить 60% його власних місячних
показників експорту у межах цих M місяців (поріг по обʼєктах).

In [622]:
L_by_store = np.nanpercentile(combined_all, 60, axis=1)
for m, L in zip(full_months, L_by_store):
    print(f"{m}: {L:.2f}")

Січень_23: 324.20
Лютий_23: 311.80
Березень_23: 324.60
Квітень_23: 278.60
Травень_23: 352.80
Червень_23: 290.00
Липень_23: 273.20
Серпень_23: 281.00
Вересень_23: 269.60
Жовтень_23: 333.00
Листопад_23: 294.60
Грудень_23: 205.40
Січень_24: 192.60
Лютий_24: 204.00
Березень_24: 225.00
Квітень_24: 214.60
Травень_24: 217.00
Червень_24: 243.40
Липень_24: 171.40
Серпень_24: 226.40
Вересень_24: 316.60
Жовтень_24: 343.60
Листопад_24: 334.20
Грудень_24: 323.00


### Завдання 10

Для кожного з M місяців розширеної таблиці:

1. знайдіть значення, що відповідає 95-му процентилю;


In [623]:
per95_by_month = np.nanpercentile(combined_all, 95, axis=0)
for m, L in zip(full_months, per95_by_month):
    print(f"{m}: {L:.2f}")

Січень_23: 440.25
Лютий_23: 452.20
Березень_23: 453.10
Квітень_23: 390.50
Травень_23: 452.35
Червень_23: 424.20
Липень_23: 415.00
Серпень_23: 467.60
Вересень_23: 398.20
Жовтень_23: 435.30
Листопад_23: 481.50
Грудень_23: 449.20
Січень_24: 445.00
Лютий_24: 403.80
Березень_24: 475.15
Квітень_24: 361.20
Травень_24: 450.20
Червень_24: 449.00
Липень_24: 446.55
Серпень_24: 395.40
Вересень_24: 401.60
Жовтень_24: 410.50
Листопад_24: 491.00
Грудень_24: 457.80


In [624]:
per95_by_month

array([ 440.250,  452.200,  453.100,  390.500,  452.350,  424.200,
        415.000,  467.600,  398.200,  435.300,  481.500,  449.200,
        445.000,  403.800,  475.150,  361.200,  450.200,  449.000,
        446.550,  395.400,  401.600,  410.500,  491.000,  457.800])

2. створіть копію таблиці та замініть кожен елемент, що перевищує порогове значення, на саме
це порогове значення;

In [625]:
clipped = np.copy(combined_all)
clipped = np.where(clipped > per95_by_month, per95_by_month, clipped)
clipped

array([[ 146.000,  352.000,  317.000,  252.000,  250.000,  378.000,
         145.000,  329.000,  180.000,  148.000,  278.000,  413.000,
         341.000,  349.000,  335.000,  356.000,  274.000,  158.000,
         372.000,  255.000,  270.000,  231.000,  nan,  nan],
       [ 174.000,  398.000,  355.000,  313.000,  241.000,  367.000,
         284.000,  253.000,  255.000,  188.000,  147.000,  286.000,
         387.000,  139.000,  378.000,  361.200,  203.000,  310.000,
         169.000,  348.000,  330.000,  226.000,  nan,  nan],
       [ 140.000,  412.000,  254.000,  388.000,  324.000,  354.000,
         348.000,  178.000,  229.000,  260.000,  269.000,  133.000,
         284.000,  166.000,  343.000,  325.000,  397.000,  344.000,
         230.000,  395.400,  243.000,  218.000,  nan,  nan],
       [ 392.000,  231.000,  142.000,  261.000,  359.000,  177.000,
         259.000,  159.000,  326.000,  263.000,  219.000,  188.000,
         289.000,  321.000,  403.000,  251.000,  168.000,  370.000,
 

3. збережіть усі інші елементи без змін.
Додатково порівняйте підсумки по місяцях «до» та «після» такого обрізання.

In [626]:
sum_before = np.nansum(combined_all, axis=0)
sum_after  = np.nansum(clipped, axis=0)

for m, s_before, s_after in zip(full_months, sum_before, sum_after):
    diff = s_after - s_before
    print(f"{m:<15} {s_before:8.2f} => {s_after:8.2f}")

Січень_23        7843.00 =>  7747.50
Лютий_23         9085.00 =>  9034.40
Березень_23      8220.00 =>  8170.20
Квітень_23       7761.00 =>  7704.00
Травень_23       9079.00 =>  9061.70
Червень_23       8751.00 =>  8692.40
Липень_23        7608.00 =>  7602.00
Серпень_23       8641.00 =>  8615.20
Вересень_23      8585.00 =>  8537.40
Жовтень_23       8118.00 =>  8031.60
Листопад_23      8179.00 =>  8159.00
Грудень_23       9064.00 =>  9035.40
Січень_24        8169.00 =>  8121.00
Лютий_24         7850.00 =>  7771.60
Березень_24      8604.00 =>  8588.30
Квітень_24       7835.00 =>  7743.40
Травень_24       7393.00 =>  7344.40
Червень_24       8772.00 =>  8731.00
Липень_24        8249.00 =>  8192.10
Серпень_24       7596.00 =>  7560.80
Вересень_24      8167.00 =>  8133.20
Жовтень_24       7292.00 =>  7235.00
Листопад_24      3864.00 =>  3857.00
Грудень_24       2701.00 =>  2684.80


### Завдання 11

Для кожного обʼєкту в розширеній таблиці обчисліть послідовність ковзної середньої з вікном 3 місяці
для таких чотирьох вікон:
* квітень–травень–червень 2024,
* травень–червень–серпень 2024,
* червень–серпень–вересень 2024,
* серпень–вересень–жовтень 2024.
<p> Подайте результат у вигляді нової таблиці з чотирма стовпчиками (по одному для кожного
вікна).

In [627]:
cols = {m: full_months.index(m) for m in full_months}

windows = [
    ["Квітень_24", "Травень_24", "Червень_24"],
    ["Травень_24", "Червень_24", "Серпень_24"],
    ["Червень_24", "Серпень_24", "Вересень_24"],
    ["Серпень_24", "Вересень_24", "Жовтень_24"],
]

result = np.zeros((combined_all.shape[0], len(windows)))

for i, j in enumerate(windows):
    idx = []
    for m in j:
        idx.append(full_months.index(m))
    result[:, i] = np.nanmean(combined_all[:, idx], axis=1)

for name, row in zip(store_names, result):
    print(f"{name:<15}" + "".join(f"{val:10.2f}" for val in row))

Україна_1          262.67    229.00    227.67    252.00
Україна_2          294.00    287.00    329.33    301.33
Україна_3          355.33    384.00    332.67    290.67
Україна_4          263.00    289.33    283.00    231.00
Україна_5          279.00    345.00    312.33    304.33
Україна_6          261.00    268.00    317.00    295.67
Україна_7          231.33    236.00    245.67    269.33
Україна_8          141.33    211.67    271.00    308.33
Україна_9          279.67    225.33    199.00    174.67
Україна_10         265.67    230.33    201.33    264.67
Україна_11         301.67    292.33    240.00    255.00
Польща_1           150.00    154.67    163.67    187.67
Польща_2           149.00    177.67    189.33    221.00
Польща_3           211.67    163.33    183.67    159.33
Польща_4           238.67    176.67    118.00    141.00
Польща_5           243.33    236.67    204.33    141.67
Польща_6           167.33    191.67    219.00    191.00
Польща_7           165.33    196.67    194.67   

### Завдання 12

Для кожного з 8 місяців (див. таблицю варіантів):

1. нормуйте замовлення по обʼєктах за цим місяцем, віднімаючи середнє і ділячи на стандартне
відхилення (вибіркове);

In [628]:
mean_by_month = np.nanmean(combined_all, axis=0)
std_by_month  = np.nanstd(combined_all, axis=0, ddof=1)

normalized = (combined_all - mean_by_month) / std_by_month

2. позначте ті комірки, де модуль нормованого значення перевищує 2;


In [629]:
mask = np.abs(normalized) > 2

3. підрахуйте, скільки таких випадків у кожному місяці та які це обʼєкти.

In [630]:
for i, m in enumerate(months_needed):
    indices = np.where(mask[:, i])[0]
    count = len(indices)
    names = [store_names[j] for j in indices]
    print(f"{m:<15} => {count} => {', '.join(names)}")

Червень_23      => 2 => Обʼєкт_1, Обʼєкт_8
Липень_23       => 0 => 
Серпень_23      => 1 => Обʼєкт_11
Вересень_23     => 1 => Обʼєкт_3
Лютий_24        => 0 => 
Березень_24     => 0 => 
Квітень_24      => 0 => 
Травень_24      => 2 => Обʼєкт_1, Обʼєкт_9


### Завдання 13

Задайте вектор відсотків очікуваного приросту експорту для M місяців у такому порядку: [3%, 5%,
2%, 0%, 1%, 4%, 2%, 1%] (відповідно для заданих у таблиці варіантів місяців).
<p> Застосуйте ці коефіцієнти до кожного елемента розширеної таблиці (помножте на 1 +коефіцієнт) та
сформуйте таблицю прогнозу експорту.

In [631]:
rates = np.array([0.03, 0.05, 0.02, 0.00, 0.01, 0.04, 0.02, 0.01])

cols = [months.index(m) for m in months_needed]
combined_growth = combined_all[:, cols]

forecast = combined_growth * (1 + rates)

print(f"{'':<15}", " ".join([f"{m:>14}" for m in months_needed]))
for name, row in zip(store_names, forecast):
    print(f"{name:<15}" + "".join(f"{v:15.2f}" for v in row))

                    Червень_23      Липень_23     Серпень_23    Вересень_23       Лютий_24    Березень_24     Квітень_24     Травень_24
Україна_1               389.34         152.25         335.58         180.00         352.49         348.40         363.12         276.74
Україна_2               378.01         298.20         258.06         255.00         140.39         393.12         376.38         205.03
Україна_3               364.62         365.40         181.56         229.00         167.66         356.72         331.50         400.97
Україна_4               182.31         271.95         162.18         326.00         324.21         419.12         256.02         169.68
Україна_5               243.08         409.50         210.12         192.00         181.80         376.48         124.44         362.59
Україна_6               299.73         137.55         165.24         193.00         263.61         392.08         295.80         144.43
Україна_7               132.87         235.20   

### Завдання 14

Для розширеної таблиці з M місяців (див. таблицю варіантів):

1. для кожного обʼєкту обчисліть сумарний експорт за всі M місяців;

In [632]:
total_by_store = np.nansum(combined_all, axis=1)
total_by_store

array([ 6129.000,  6120.000,  6250.000,  5780.000,  6545.000,  5794.000,
        5757.000,  5781.000,  5753.000,  6248.000,  5848.000,  3905.000,
        4205.000,  4163.000,  4156.000,  4469.000,  4379.000,  4252.000,
        3873.000,  4311.000,  6724.000,  5493.000,  6696.000,  5649.000,
        6853.000,  5306.000,  7856.000,  5738.000,  7390.000,  7013.000,
        5969.000,  6088.000,  6933.000])

2. відсортуйте обʼєкти за спаданням цієї суми;

In [633]:
indices = np.argsort(total_by_store)[::-1]
top5 = indices[:5]
top5

array([26, 28, 29, 32, 24])

3. випишіть п’ять обʼєктів із найбільшим сумарним експортом, зазначивши назви та значення
сум.

In [634]:
for i in top5:
    print(f"{store_names[i]:<10} -> {total_by_store[i]:>10.2f}")

Обʼєкт_7   ->    7856.00
Обʼєкт_9   ->    7390.00
Обʼєкт_10  ->    7013.00
Обʼєкт_13  ->    6933.00
Обʼєкт_5   ->    6853.00


### Завдання 15

1. Випадковим чином замініть 5% елементів розширеної таблиці на позначку «немає даних».

In [635]:
mask = rng.random(size=combined_all.shape) < 0.05
combined_nan = combined_all.copy()
combined_nan[mask] = np.nan

2. Для кожного з M місяців обчисліть середній експорт, ігноруючи комірки з позначкою «немає
даних».

In [636]:
mean_by_month = np.nanmean(combined_nan, axis=0)
mean_by_month

array([ 248.677,  266.774,  274.852,  246.034,  286.167,  258.333,
        245.419,  267.871,  255.312,  253.688,  268.071,  283.250,
        259.967,  245.967,  282.793,  240.906,  257.571,  263.188,
        277.414,  233.452,  256.700,  233.500,  351.273,  270.100])

3. Додатково порахуйте частку пропусків у кожному місяці (скільки відсотків комірок позначено
як «немає даних»).

In [637]:
missing = np.sum(np.isnan(combined_nan), axis=0) / combined_nan.shape[0] * 100
for m, val, proc in zip(months_needed, mean_by_month, missing):
    print(f"{m:<10}\t{val:10.2f}\t{proc:10.2f}%")

Червень_23	    248.68	      6.06%
Липень_23 	    266.77	      6.06%
Серпень_23	    274.85	     18.18%
Вересень_23	    246.03	     12.12%
Лютий_24  	    286.17	      9.09%
Березень_24	    258.33	      9.09%
Квітень_24	    245.42	      6.06%
Травень_24	    267.87	      6.06%
